{% set version = "0.3.1" %}

package:
  name: komplexity
  version: {{ version }}

source:
  url: https://github.com/eclarke/komplexity/archive/v{{ version }}.tar.gz
  fn: komplexity-{{ version }}.tar.gz
  sha256: 5e83afad1fdb1937a91e0da71b772ab4c65936bc1c9626b7bc603667cb7846af

build:
  number: 1
  string: musl

requirements:
  build:
    - rust

  run:
    - rust

test:
  commands:
    - kz -h

about:
  home: https://github.com/eclarke/komplexity

